name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout # Clone your repository into the working directory of your VM
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet # Used to reference this step from the steps variable that github actions provides
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Leslie # Input for this action
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}" # Reference the greet step above