name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # Arbitrary value that can be whatever we want
        node_version: [6, 8, 10]
      # fail-fast: true
      # # Limit the number of jobs running in parallel in this matrix
      # max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          # Reference your arbitrary values in the matrix context
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: node -v
