name: Shell Commands 

# on: [push]
on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    # Increase/decrease the amount of time a job is allowed to take. Default is 6 hours
    # timeout-minutes: 360
    steps: 
      - name: echo a string
        run: echo "Hello World"
        # Max number of minutes before github kills the process for this step
        # timeout-minutes: 360
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windwos-commands:
    runs-on: windows-latest
    # Run jobs in sequence
    # Only run run-windwos-commands job after the run-shell-command job finishes
    needs: ["run-shell-command"] 
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash